AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config.ru'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Metrics/LineLength:
  Max: 100