AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config.ru'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/FormatStringToken:
  Enabled: false
Metrics/MethodLength:
  Max: 20
